async function ep10(){
  await T.say('その客が階段を降りてくる前に、俺は手を止めた。','narr');
  await T.say('足音に混じって、嗅ぎ慣れた匂いがした。古い端末の焼ける匂い。長く記憶を読み続けた機械だけがまとう匂いだ。','narr');
  T.sp();
  await T.say('それは俺の店にも、染みついている匂いだった。', 'narr');
  await T.say('客じゃない。同じ仕事の人間が来た。それも、相当、長くやってる奴だ。', 'narr');
  T.sp();
  await T.tap();

  await Scene.load('CLIENT_ep0');
  knock(); await T.sleep(300);
  await T.say('ノックは一つ。叩き慣れた、事務的な音だった。','narr');
  await T.dlg('「開いてる」');
  T.sp();
  Scene.set('CLIENT_ep0');
  await T.sleep(400);
  await T.say('入ってきたのは、骨ばった老人だった。俺と同じ作業着の上に、すり切れたコートを羽織っている。','narr');
  await T.say('指先が、長年ケーブルを握ってきた形に固まっていた。一目でわかる。こいつも記憶屋だ。','narr');
  T.sp();
  await T.dlg('「座ってくれ。料金は前払い。作業が始まれば――」');
  await T.npc('「その口上は省け」');
  await T.say('老人が片手で制した。','narr');
  T.sp();
  await T.npc('「こっちも同じ商売を、四十年やってる。前払いも、取り消し無しも、骨身に染みてるさ」');
  await T.dlg('「……そうかい。同業に出す茶はないが、椅子は空いてる」');
  T.sp();
  await T.tap();

  await T.dlg('「四十年選手のあんたが、わざわざ俺の店の戸を叩く理由は」');
  await T.npc('「決まってる。自分の頭は、自分じゃ読めないからだ」');
  T.sp();
  await T.say('老人は軋む椅子に腰を下ろした。コートの下から、痩せた首筋の古いポートがのぞいた。','narr');
  T.sp();
  await T.npc('「あんたも知ってるだろう。リンクは外から挿すもんだ。自分のポートに、自分のケーブルは回らない」');
  await T.npc('「だから俺たちは、自分の頭の掃除だけは、できない」');
  T.sp();
  await T.dlg('「で。何を掃除したい」');
  await T.npc('「俺を、俺に戻してくれ」');
  T.sp();
  await T.say('老人の目が、暗い端末の光を映した。','narr');
  T.sp();
  await T.npc('「四十年、客の頭に入り続けた。一人読むたび、ほんの少し、相手の澱が残る。ほんのひとさじだ」');
  await T.npc('「だが千人を超えたあたりから、わからなくなった。どれが俺の記憶で、どれが客の置き土産か」');
  await T.npc('「親父の声を思い出す。だが、あれは本当に俺の親父か。どこかの客の親父じゃないのか」');
  T.sp();
  await T.tap();

  await T.dlg('「今さら、自分を取り戻したい理由は」');
  await T.npc('「もう、引退する。最後くらい、俺自身に戻って死にたい」');
  T.sp();
  await T.npc('「頼みは一つだ。俺の中の、客の澱を、全部消してくれ」');
  await T.npc('「他人が紛れ込む前の、生身の俺だけを残してほしい」');
  T.sp();
  await T.say('千人分の他人を被った男。底に沈んだ本物の自分を、掘り出してくれという話だ。', 'narr');
  await T.say('EP4の女優は、一粒の借りものに苦しんでいた。だがこいつは違う。一粒どころか、もう、澱のほうが本体だ。', 'narr');
  T.sp();
  await T.say('俺はケーブルを引き寄せた。同業の頭を読むのは、初めてだ。','narr');
  await T.dlg('「読む。澱と、地金の境目を、確かめてからだ」');
  await T.npc('「気をつけろよ。同業者を読むと――向こうからも、こっちが見える」');
  T.sp();
  await T.say('その意味を確かめる前に、俺はケーブルを老人の首筋へ挿していた。','narr');
  await T.sleep(400);

  await linkGlitch();
  linkOn();
  Scene.clearText();
  await msys('[ LINK ESTABLISHED ]');
  await msys('[ WARNING: PEER-TO-PEER LINK ]');
  await msys('[ READING NEURAL ARCHIVE... ]');
  await T.sleep(300);

  await mlog('...親父に殴られた夜。――いや、これは三番目の客の親父だ。');
  await mlog('...初恋の女の横顔。――どこかで買い取った、誰かの初恋。');
  await mlog('...戦争の記憶。俺は戦争になど、行っていない。たぶん。');
  await mlog('...海を見た。あの海は、俺の海か。客の海か。');
  await mlog('...どれもこれも、手触りがある。どれもこれも、確信がない。');
  await T.sleep(200);
  await T.tap();

  await mlog('...いちばん底に、小さな子供がいる。');
  await mlog('...名前を、忘れている。これだけは、確かに俺だ。たぶん。');
  await mlog('...だがその周りには、もう、何も残っていない。');
  await mlog('...澱を消せば、この子供が残る。――本当に、残るのか。');
  await T.sleep(200);

  glitch(500);
  await T.sleep(200);
  await msys('[ERR] RESIDUAL GHOST DETECTED', '#ff2244');
  await msys('[ALERT] REVERSE-READ IN PROGRESS', '#ff2244');
  await T.sleep(200);
  await T.say('視界が真緑に染まった。読んでいるのに、読まれている。', 'narr');
  await T.say('老人の澱が俺に流れ込み、俺の中身が老人へ逆流する。', 'narr');
  await T.say('――その瞬間、椅子の老人が、息を呑んだ。', 'narr');
  T.sp();
  await T.npc('「……おい。あんた」');
  await T.npc('「あんたの中は……静かすぎる」');
  await T.npc('「四十年読んできた俺にも、こんな頭は、見たことがない。澱が、一滴もない」');
  await T.npc('「まるで――誰も住んだことのない、新品の部屋だ」');
  T.sp();
  await T.say('黙れ。', 'narr');
  await T.say('読み返すな。俺の中を、覗くな。', 'narr');
  T.sp();
  await T.tap();

  await T.say('俺は、力ずくでリンクを切った。','narr');
  linkOff();
  await linkGlitch();
  Scene.clearText();
  await msys('[ LINK TERMINATED ]');
  T.sp();
  await T.sleep(400);

  await T.say('端末の光が荒く明滅して、落ち着いた。','narr');
  await T.say('老人は俺をじっと見ていた。客を見る目じゃない。同じ穴の何かを、見透かす目だ。','narr');
  T.sp();
  await T.dlg('「……読んだ。あんたの底に、名前を忘れた子供が一人。それが地金だ」');
  await T.dlg('「だが言っておく。澱を全部消したら、その子供が一人で残るとは限らない」');
  await T.dlg('「四十年だ。あんたはもう、澱でできてる。客の親父も、誰かの初恋も、戦争も、全部ひっくるめて、今のあんただ」');
  T.sp();
  await T.npc('「……他人の寄せ集めが、俺だと言うのか」');
  await T.dlg('「そうは言わん。だが、寄せ集めたのは、あんたの手だ」');
  await T.dlg('「千人を読んで、千人を背負って、それでも壊れずに四十年立ってた。その背骨だけは、間違いなくあんたのものだ」');
  T.sp();
  await T.npc('「消せば、軽くなる。だが――その背骨も、抜けるかもしれんと言いたいのか」');
  await T.dlg('「ああ。最悪、子供一人すら、残らないかもしれん」');
  T.sp();
  await T.say('老人は、骨ばった指を、ゆっくり組んだ。','narr');
  T.sp();
  await T.npc('「あんたなら、どうする」');
  await T.dlg('「……俺は、自分を読んだことがない」');
  await T.dlg('「だから、答えられん。これは、あんたが決めることだ」');
  T.sp();
  await T.tap();

  const ch = await showChoices('[ 消す ]', '[ 残す ]');
  T.sp();
  if(ch==='ERASE') await ep10EraseEnd();
  else             await ep10KeepEnd();
  await ep10Epilogue();
}

async function ep10EraseEnd(){
  await msys('[ ERASING RESIDUE... ]');
  await T.say('俺は、澱の層に、削除のマーカーを敷いた。','narr');
  await T.say('客の親父。誰かの初恋。覚えのない海と戦争。四十年分の他人を、底に向かって一枚ずつ流していく。','narr');
  T.sp();
  await T.say('剥がすたび、層が薄くなる。そして底の子供が、近づいてくる。', 'narr');
  await T.say('だが――子供の輪郭は、澱が支えていた。澱を抜くほど、子供まで、ほどけていく。', 'narr');
  glitch(300);
  await T.sleep(350);
  await msys('[ COMPLETE ]', '#00ff55');
  T.sp();
  await T.say('老人が、ゆっくり目を開けた。その目から、何かが綺麗に抜け落ちていた。','narr');
  await T.npc('「……静かだ」');
  await T.npc('「ああ、静かだな。誰の声も、しない」');
  T.sp();
  await T.dlg('「あんたの底の子供は」');
  await T.npc('「……子供? なんの話だ」');
  T.sp();
  await T.say('澱と一緒に、地金まで流れた。', 'narr');
  await T.say('老人は立ち上がった。背筋は伸びていたが、目の焦点が、どこにも合っていなかった。','narr');
  await T.npc('「……俺は、何をしに来たんだったか。まあ、いい。帰るよ」');
  T.sp();
  await T.say('老人は、すり切れたコートの裾を引いて出ていった。来たときより、ずっと軽い足取りで。','narr');
  Scene.set('IDLE');
  T.sp();
  await T.say('こいつは自分に戻ったんじゃない。誰でもなくなったんだ。', 'narr');
  await T.say('――他人を捨てきった頭は、新品の部屋だ。どこかで、見たことがある。今朝、硝子の中で。', 'narr');
}

async function ep10KeepEnd(){
  await T.say('俺はケーブルを抜いた。マーカーは敷かなかった。','narr');
  T.sp();
  await T.npc('「……消さないのか」');
  await T.dlg('「消しちまえば、あんたごと消える。澱もろともな」');
  T.sp();
  await T.say('老人が、組んだ指をほどいた。','narr');
  T.sp();
  await T.dlg('「あんたは、他人が紛れ込む前の自分に戻りたいと言った。だが、その自分はもう、底に小さく沈んでるだけだ」');
  await T.dlg('「四十年、千人を背負って歩いた。その重みが、今のあんたの形を決めてる」');
  await T.dlg('「澱を消すのは、自分に戻ることじゃない。今のあんたを、まるごと捨てることだ」');
  T.sp();
  await T.npc('「……他人だらけの、こんな頭でも、抱えて死ねと」');
  await T.dlg('「ああ。あんたが読んだ千人は、もう、あんたの中でしか生きてない」');
  await T.dlg('「あんたが澱を抱えて死ねば、その千人も、ちゃんと一緒に看取られる」');
  await T.dlg('「悪い死に方じゃない。記憶屋の、まっとうな店じまいだ」');
  T.sp();
  await T.say('老人は長いこと黙っていた。やがて、乾いた音で笑った。','narr');
  await T.npc('「……千人を、看取る、か」');
  await T.npc('「四十年やって、初めて、自分の商売を、まともに言われた気がするよ」');
  T.sp();
  await T.say('老人は立ち上がり、戸口で振り返った。同業の顔で、俺を見た。','narr');
  await T.npc('「あんた、まだ若い。一つだけ、年寄りの忠告だ」');
  await T.npc('「客ばかり読んでないで――いつか、自分も、読んでみろ」');
  await T.npc('「自分が何でできてるか、知らないままってのは……あんまり、いい死に方じゃない」');
  T.sp();
  await T.say('老人は、すり切れたコートを翻して、階段を上っていった。','narr');
  Scene.set('IDLE');
}

async function ep10Epilogue(){
  Scene.set('IDLE');
  await T.sleep(500);
  await T.say('古い端末の焼ける匂いが、しばらく店に残っていた。俺の店の匂いと、同じ匂いだ。','narr');
  T.sp();
  await T.tap();
  await T.say('記憶屋は、他人の頭を覗いて暮らす。','narr');
  await T.say('人の澱を毎晩すくって、これは消す、これは棚へと、勝手に値踏みをする。','narr');
  await T.say('そうやって四十年もやれば、自分が他人でできていく。あの老人は、その成れの果てだった。','narr');
  T.sp();
  await T.say('だが、おかしな話だ。','narr');
  await T.say('俺も、ずっと、この商売をやっている。','narr');
  await T.say('なのに、俺の中には澱が一滴もないと、あいつは言った。新品の部屋だと。','narr');
  T.sp();
  await T.tap();
  await T.say('千人を読んで、何も残らない頭なんて、あるか。', 'narr');
  await T.say('――いや。最初から、何も入っていなければ、残りようがない。', 'narr');
  T.sp();
  await T.say('俺は、自分の首筋のポートに指を当てた。冷たい端子が、そこにある。','narr');
  await T.say('読めば、わかる。俺が客なのか、店なのか。誰の澱でできているのか。あるいは、何も入っていない、新品の部屋なのか。', 'narr');
  await T.say('――だが、自分のポートに、自分のケーブルは回らない。あの男が、自分で言ったとおりだ。', 'narr');
  await T.say('知るには、誰かに挿させるしかない。さっき、俺がこの男にしたようにな。', 'narr');
  T.sp();
  await T.say('足元で、さっきまで老人を読んでいたケーブルが、とぐろを巻いている。','narr');
  await T.say('こいつを、誰かの手に握らせればいい。一度でいい。俺を、読んでくれと。', 'narr');
  T.sp();
  await T.say('――手が、止まった。婆さんのときと、同じ場所で。', 'narr');
  await T.say('まだ、いい。', 'narr');
  await T.say('知らないままのほうが、まだ、店を開けていられる。', 'narr');
  T.sp();
  await T.say('俺はケーブルを、暗がりへ蹴った。緑の光が瞬く。今夜の客は、もう、来ない。','narr');
  T.sp();
  await Scene.addText('[ END OF LOG: EP.10  PEER ]', '#ffaa00', 1);
  await Scene.addText('同業', '#cfe8cf', 3, 'big');
  await T.sleep(2500);
}
